// ============================================================================
// VGK Property Command - Initial Demo Data
// Sample data for Ugandan property management context
// ============================================================================

import {
  OnePageStrategicPlan,
  Rock,
  KPI,
  CriticalNumber,
  Property,
  Tenant,
  Account,
  Vendor,
} from '../types';
import { getTodayISO, getCurrentQuarter, addMonths, addDays } from '../utils/helpers';

const today = getTodayISO();

// ============================================================================
// STRATEGIC PLANNING DATA
// ============================================================================

export const initialOPSP: OnePageStrategicPlan = {
  id: 'opsp_001',
  coreValues: [
    'Excellence in Service',
    'Integrity & Transparency',
    'Respect for Tenants & Partners',
    'Continuous Improvement',
    'Community Development',
  ],
  corePurpose: 'To provide exceptional property management services that create lasting value for property owners while enhancing the quality of life for tenants in Uganda.',
  bhag: 'By 2035, become the most trusted property management firm in East Africa, managing over 10,000 units across Uganda, Kenya, and Tanzania.',
  threeYearPicture: 'By 2027, we will manage 500+ units across Kampala with 95%+ occupancy, industry-leading tenant satisfaction scores, and IFRS-compliant financial systems that set the standard for property management in Uganda.',
  annualTheme: '2024: Building Strong Foundations',
  quarterlyTheme: `${getCurrentQuarter()}: Systems & Processes Excellence`,
  lastUpdated: today,
};

export const initialRocks: Rock[] = [
  {
    id: 'rock_001',
    description: 'Implement VGK Property Command platform with full GL integration',
    owner: 'Operations Team',
    quarter: getCurrentQuarter(),
    status: 'on-track',
    progress: 75,
    dueDate: addMonths(today, 1),
    createdAt: addDays(today, -60),
  },
  {
    id: 'rock_002',
    description: 'Achieve 95% rent collection rate across all properties',
    owner: 'Finance Team',
    quarter: getCurrentQuarter(),
    status: 'on-track',
    progress: 82,
    dueDate: addMonths(today, 1),
    createdAt: addDays(today, -60),
  },
  {
    id: 'rock_003',
    description: 'Reduce maintenance response time to <12 hours average',
    owner: 'Maintenance Team',
    quarter: getCurrentQuarter(),
    status: 'at-risk',
    progress: 60,
    dueDate: addMonths(today, 1),
    createdAt: addDays(today, -60),
  },
];

export const initialKPIs: KPI[] = [
  {
    id: 'kpi_001',
    name: 'Portfolio Occupancy Rate',
    category: 'operational',
    currentValue: 92.5,
    targetValue: 95.0,
    unit: '%',
    frequency: 'monthly',
    status: 'YELLOW',
    trend: 'up',
    lastUpdated: today,
    history: [
      { date: addMonths(today, -3), value: 88.0 },
      { date: addMonths(today, -2), value: 90.0 },
      { date: addMonths(today, -1), value: 91.5 },
      { date: today, value: 92.5 },
    ],
  },
  {
    id: 'kpi_002',
    name: 'Rent Collection Rate',
    category: 'financial',
    currentValue: 87.3,
    targetValue: 95.0,
    unit: '%',
    frequency: 'monthly',
    status: 'RED',
    trend: 'stable',
    lastUpdated: today,
    history: [
      { date: addMonths(today, -3), value: 86.5 },
      { date: addMonths(today, -2), value: 87.0 },
      { date: addMonths(today, -1), value: 87.5 },
      { date: today, value: 87.3 },
    ],
  },
  {
    id: 'kpi_003',
    name: 'Average Maintenance Response Time',
    category: 'operational',
    currentValue: 18.5,
    targetValue: 24.0,
    unit: 'hours',
    frequency: 'weekly',
    status: 'GREEN',
    trend: 'down',
    lastUpdated: today,
    history: [
      { date: addDays(today, -21), value: 22.0 },
      { date: addDays(today, -14), value: 20.5 },
      { date: addDays(today, -7), value: 19.0 },
      { date: today, value: 18.5 },
    ],
  },
  {
    id: 'kpi_004',
    name: 'Operating Expense Ratio',
    category: 'financial',
    currentValue: 42.0,
    targetValue: 45.0,
    unit: '%',
    frequency: 'monthly',
    status: 'GREEN',
    trend: 'stable',
    lastUpdated: today,
    history: [
      { date: addMonths(today, -3), value: 43.5 },
      { date: addMonths(today, -2), value: 42.5 },
      { date: addMonths(today, -1), value: 42.0 },
      { date: today, value: 42.0 },
    ],
  },
];

export const initialCriticalNumbers: CriticalNumber[] = [
  {
    id: 'cn_001',
    name: 'Monthly Collected Rent',
    description: 'Actual rent collected (not billed) - cash in hand',
    currentValue: 18500000,
    unit: 'UGX',
    isVital20Percent: true,
    lastUpdated: today,
    history: [
      { date: addMonths(today, -3), value: 17200000 },
      { date: addMonths(today, -2), value: 17800000 },
      { date: addMonths(today, -1), value: 18200000 },
      { date: today, value: 18500000 },
    ],
  },
  {
    id: 'cn_002',
    name: 'Vacant Units',
    description: 'Number of vacant units requiring immediate action',
    currentValue: 3,
    unit: 'units',
    isVital20Percent: true,
    lastUpdated: today,
    history: [
      { date: addMonths(today, -3), value: 5 },
      { date: addMonths(today, -2), value: 4 },
      { date: addMonths(today, -1), value: 3 },
      { date: today, value: 3 },
    ],
  },
  {
    id: 'cn_003',
    name: 'Overdue Payments',
    description: 'Total amount of overdue rent (>30 days)',
    currentValue: 2400000,
    unit: 'UGX',
    isVital20Percent: true,
    lastUpdated: today,
    history: [
      { date: addMonths(today, -3), value: 3200000 },
      { date: addMonths(today, -2), value: 2800000 },
      { date: addMonths(today, -1), value: 2600000 },
      { date: today, value: 2400000 },
    ],
  },
];

// ============================================================================
// PROPERTY & TENANT DATA
// ============================================================================

export const initialProperties: Property[] = [
  {
    id: 'prop_001',
    name: 'Kololo Heights',
    address: 'Plot 42, Kololo Road, Kampala',
    type: 'residential',
    status: 'active',
    totalUnits: 12,
    occupiedUnits: 11,
    squareFeet: 18000,
    purchasePrice: 1200000000,
    purchaseDate: '2020-03-15',
    currentValue: 1500000000,
    monthlyIncome: 9600000,
    monthlyExpenses: 3800000,
    managementFee: 960000,
    notes: 'Premium apartments, high-end market',
    createdAt: '2020-03-15T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'prop_002',
    name: 'Ntinda Plaza',
    address: 'Ntinda Shopping Complex, Kampala',
    type: 'commercial',
    status: 'active',
    totalUnits: 8,
    occupiedUnits: 7,
    squareFeet: 12000,
    purchasePrice: 800000000,
    purchaseDate: '2021-06-20',
    currentValue: 950000000,
    monthlyIncome: 7200000,
    monthlyExpenses: 2400000,
    managementFee: 720000,
    notes: 'Retail and office spaces',
    createdAt: '2021-06-20T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'prop_003',
    name: 'Bugolobi Residences',
    address: '15 Luthuli Avenue, Bugolobi, Kampala',
    type: 'residential',
    status: 'active',
    totalUnits: 20,
    occupiedUnits: 19,
    squareFeet: 24000,
    purchasePrice: 900000000,
    purchaseDate: '2019-11-10',
    currentValue: 1100000000,
    monthlyIncome: 12000000,
    monthlyExpenses: 5200000,
    managementFee: 1200000,
    notes: 'Family apartments, well-established',
    createdAt: '2019-11-10T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
];

export const initialTenants: Tenant[] = [
  {
    id: 'tenant_001',
    propertyId: 'prop_001',
    unitNumber: 'A-101',
    name: 'Sarah Nakamya',
    email: 'sarah.nakamya@email.com',
    phone: '+256700123456',
    leaseStartDate: '2023-01-01',
    leaseEndDate: '2024-12-31',
    monthlyRent: 800000,
    deposit: 1600000,
    paymentStatus: 'paid',
    lastPaymentDate: addDays(today, -5),
    lastPaymentAmount: 800000,
    outstandingBalance: 0,
    notes: 'Excellent tenant, always pays on time',
    createdAt: '2023-01-01T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'tenant_002',
    propertyId: 'prop_001',
    unitNumber: 'A-102',
    name: 'John Okello',
    email: 'j.okello@email.com',
    phone: '+256700234567',
    leaseStartDate: '2023-06-01',
    leaseEndDate: '2025-05-31',
    monthlyRent: 800000,
    deposit: 1600000,
    paymentStatus: 'due',
    lastPaymentDate: addDays(today, -35),
    lastPaymentAmount: 800000,
    outstandingBalance: 800000,
    notes: 'Payment due for current month',
    createdAt: '2023-06-01T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'tenant_003',
    propertyId: 'prop_002',
    unitNumber: 'Shop-101',
    name: 'Kampala Electronics Ltd',
    email: 'info@kampalaelectronics.com',
    phone: '+256700345678',
    leaseStartDate: '2022-03-01',
    leaseEndDate: '2025-02-28',
    monthlyRent: 1200000,
    deposit: 3600000,
    paymentStatus: 'overdue',
    lastPaymentDate: addDays(today, -65),
    lastPaymentAmount: 1200000,
    outstandingBalance: 2400000,
    notes: 'Two months overdue - follow up required',
    createdAt: '2022-03-01T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
];

// ============================================================================
// VENDOR DATA
// ============================================================================

export const initialVendors: Vendor[] = [
  {
    id: 'vendor_001',
    name: 'Kampala Plumbing Services',
    category: 'plumbing',
    contactPerson: 'Moses Wabwire',
    phone: '+256700111222',
    email: 'moses@kampalaplumbing.com',
    address: 'Industrial Area, Kampala',
    rating: 4.5,
    totalJobsCompleted: 24,
    averageResponseTime: 8.5,
    isPreferred: true,
    notes: 'Reliable, fast response, fair pricing',
    createdAt: '2023-01-15T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'vendor_002',
    name: 'Bright Electrical Solutions',
    category: 'electrical',
    contactPerson: 'David Ssemakula',
    phone: '+256700222333',
    email: 'david@brightelectrical.com',
    address: 'Ntinda, Kampala',
    rating: 4.8,
    totalJobsCompleted: 18,
    averageResponseTime: 6.2,
    isPreferred: true,
    notes: 'Excellent work quality, certified electrician',
    createdAt: '2023-02-10T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'vendor_003',
    name: 'Green Gardens Landscaping',
    category: 'landscaping',
    contactPerson: 'Grace Namukasa',
    phone: '+256700333444',
    email: 'grace@greengardens.com',
    address: 'Entebbe Road, Kampala',
    rating: 4.2,
    totalJobsCompleted: 12,
    averageResponseTime: 24.0,
    isPreferred: false,
    notes: 'Good quality but slower response',
    createdAt: '2023-03-05T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
];

// ============================================================================
// CHART OF ACCOUNTS (IFRS-compliant)
// ============================================================================

export const initialAccounts: Account[] = [
  // ASSETS
  {
    id: 'acc_1000',
    code: '1000',
    name: 'Cash and Cash Equivalents',
    category: 'asset',
    type: 'current-asset',
    normalBalance: 'debit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'acc_1100',
    code: '1100',
    name: 'Accounts Receivable - Rent',
    category: 'asset',
    type: 'current-asset',
    normalBalance: 'debit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'acc_1500',
    code: '1500',
    name: 'Investment Property',
    category: 'asset',
    type: 'investment-property',
    normalBalance: 'debit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },

  // LIABILITIES
  {
    id: 'acc_2000',
    code: '2000',
    name: 'Accounts Payable',
    category: 'liability',
    type: 'current-liability',
    normalBalance: 'credit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'acc_2100',
    code: '2100',
    name: 'Tenant Deposits Payable',
    category: 'liability',
    type: 'current-liability',
    normalBalance: 'credit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },

  // EQUITY
  {
    id: 'acc_3000',
    code: '3000',
    name: 'Owner\'s Capital',
    category: 'equity',
    type: 'capital',
    normalBalance: 'credit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'acc_3100',
    code: '3100',
    name: 'Retained Earnings',
    category: 'equity',
    type: 'retained-earnings',
    normalBalance: 'credit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },

  // INCOME
  {
    id: 'acc_4000',
    code: '4000',
    name: 'Rental Income',
    category: 'income',
    type: 'rental-income',
    normalBalance: 'credit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'acc_4100',
    code: '4100',
    name: 'Late Payment Fees',
    category: 'income',
    type: 'other-income',
    normalBalance: 'credit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },

  // EXPENSES
  {
    id: 'acc_5000',
    code: '5000',
    name: 'Maintenance and Repairs',
    category: 'expense',
    type: 'operating-expense',
    normalBalance: 'debit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'acc_5100',
    code: '5100',
    name: 'Utilities',
    category: 'expense',
    type: 'operating-expense',
    normalBalance: 'debit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'acc_5200',
    code: '5200',
    name: 'Property Management Fees',
    category: 'expense',
    type: 'administrative-expense',
    normalBalance: 'debit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'acc_5300',
    code: '5300',
    name: 'Insurance',
    category: 'expense',
    type: 'operating-expense',
    normalBalance: 'debit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
  {
    id: 'acc_5400',
    code: '5400',
    name: 'Property Taxes',
    category: 'expense',
    type: 'operating-expense',
    normalBalance: 'debit',
    currentBalance: 0,
    isActive: true,
    createdAt: today + 'T10:00:00Z',
    updatedAt: today + 'T10:00:00Z',
  },
];
